### ISSUE TITLE
Running on a Pi3 with Dietpi

### ISSUE THREAD

**Issue by ajhawley** [ssovit/rpi3-plex-sonarr-radarr-cardigann-deluge#1]
i have had major issues with dietpis built in app, they always fail due to permission errors

anyway i decide id give the script a go on diet pi

for this to work it took more than i thought, first off i downloaded the setup.sh with wget not noticing i needed to have /files/ on the device, DOH!

anyway i downloaded the zip and unziped and started the install

mostly a disaster due to it wanting to use the user and group PI

so i started again and added the user and group PI

this worked and installed everything without error except deluge.

so i manually installed it using the commands from the setup.sh script

sudo apt-get install deluged deluge-web deluge-console -ys

kept getting errors so i dropped the -ys

then the next few bits of code were fine

sudo -u pi deluged (gives a lib torrent warning)

anyway i have managed to get it working without changing too much

but i think it would be good if you could look at getting the script to check for user or just adduser pi and maybe drop the -ys from the APT-get deluge (not sure what its for) yeah im abit of a n00b

**Comment by ssovit** [comment]
Please feel free to create pull request with the fixes you have.
